// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Layout.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20211207134722_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Leeftijd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lengte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasOne("Student", null)
                        .WithMany("Vrienden")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Navigation("Vrienden");
                });
#pragma warning restore 612, 618
        }
    }
}
